// VIVA Cycle - keep sensitive app data out of Android backups (config plugin, runs at build time).
//
// Backup policy: VIVA Cycle's data (all AsyncStorage records) is NOT backed up or transferred.
//  - app.json sets android.allowBackup = false: Android 11 and older do no backup or restore at all,
//    and Android 12+ do no cloud (Google) backup.
//  - Some manufacturers' Android 12+ phones still allow device-to-device transfer when only
//    allowBackup="false" is set (developer.android.com/identity/data/autobackup), so this plugin
//    also adds data-extraction rules that exclude every app storage domain from BOTH cloud backup
//    and device transfer.
// Expo has no app.json setting for data-extraction rules, hence this small local plugin.
// It only changes the generated android/ folder; it never touches stored data or keys.

const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');

const RULES_NAME = 'viva_data_extraction_rules';

/** Every storage location Android backs up (all nine documented domains). */
const DOMAINS = [
  'root', 'file', 'database', 'sharedpref', 'external',
  'device_root', 'device_file', 'device_database', 'device_sharedpref',
];

function rulesXml() {
  const excludes = DOMAINS.map((d) => `    <exclude domain="${d}" path="." />`).join('\n');
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by plugins/withNoBackup.js: VIVA Cycle data is never backed up or transferred. -->',
    '<data-extraction-rules>',
    '  <cloud-backup>',
    excludes,
    '  </cloud-backup>',
    '  <device-transfer>',
    excludes,
    '  </device-transfer>',
    '</data-extraction-rules>',
    '',
  ].join('\n');
}

/** Point the <application> at the rules (and keep allowBackup off even if a template sets it). */
function setBackupAttributes(androidManifest) {
  const app = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  app.$['android:allowBackup'] = 'false';
  app.$['android:dataExtractionRules'] = `@xml/${RULES_NAME}`;
  return androidManifest;
}

function withNoBackup(config) {
  config = withAndroidManifest(config, (c) => {
    c.modResults = setBackupAttributes(c.modResults);
    return c;
  });
  config = withDangerousMod(config, [
    'android',
    async (c) => {
      const dir = path.join(c.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, RULES_NAME + '.xml'), rulesXml());
      return c;
    },
  ]);
  return config;
}

module.exports = withNoBackup;
module.exports.rulesXml = rulesXml;
module.exports.setBackupAttributes = setBackupAttributes;
module.exports.DOMAINS = DOMAINS;
module.exports.RULES_NAME = RULES_NAME;
